import axios from 'axios'
import util from 'util'

const server = 'http://cmpt371g4.usask.ca:8081'

function getImage (Id) {
  return new Promise((resolve, reject) => {
    axios.get(server + '/api/images/' + Id)
      .then(function (responce) {
        resolve(server + responce.data.path)
      })
      .catch(function (err) {
        console.log(util.inspect(err, false, null))
        reject(err)
      })
  })
}

function uploadImage (image) {
  return new Promise((resolve, reject) => {
    console.log(util.inspect(image, false, null))
    var formData = new FormData()
    formData.append('image', image)
    // token currently is generated by postman, will upadte after user part is done
    formData.append('token', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1MjE1ODc3MjAsImV4cCI6MTUyMTU5MTMyMH0.VZ3SOhs-pmEzET1TCKFnMDgHaiE-KEd0X8Sd7TbRn1c')
    // var token = this.$store.getters.token
    // formData.append('token', token)
    axios.put(server + '/api/images', formData)
      .then(function (responce) {
        resolve(responce.data)
      })
      .catch(function (err) {
        console.log(util.inspect(err, false, null))
        reject(err)
      })
  })
}

function deleteImage (Id) {
  return new Promise((resolve, reject) => {
    axios.delete(server + '/api/images/' + Id, {
      data:
      {
        // token: this.$store.getters.token
        // token currently is generated by postman, will upadte after user part is done
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1MjE1ODc3MjAsImV4cCI6MTUyMTU5MTMyMH0.VZ3SOhs-pmEzET1TCKFnMDgHaiE-KEd0X8Sd7TbRn1c'
      }
    })
      .then(function (responce) {
        resolve()
      })
      .catch(function (err) {
        reject(err)
      })
  })
}

export default {
  getImage,
  uploadImage,
  deleteImage
}
